name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  docker:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Packages
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: wendyliga
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        if: github.event_name != 'pull_request'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/wendyliga/slack-chatgpt-qa-bot
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags') }}
            type=edge,enable=${{ github.ref == 'refs/heads/main' }}
      - name: Build
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v2

      - name: Deploy edge
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Deploy release
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}